net:
  port: 27017
  bindIpAll: true
security:
  authorization: enabled
  keyFile: /data.tf/replica.key
storage:
  dbPath: /data.tf/db
replication:
  replSetName: rs
systemLog:
  verbosity: 1
  traceAllExceptions: true