#!/usr/bin/env python3
"""Emit per-tenant egress NetworkPolicies from registry.yaml (CU-86aj8pvgx, MT-5).

Each tenant in registry.yaml becomes a default-deny **egress** NetworkPolicy
that allowlists only DNS + the konfig gRPC endpoint (plus per-tenant extras),
so a compromised tenant workload cannot exfiltrate to arbitrary destinations.
konfig does not enforce this — a policy-enforcing CNI does; this script only
emits the manifests. The overlay is off by default (see README.md).

Usage:
    python3 generate.py          # (re)write manifests next to registry.yaml
    python3 generate.py --check  # exit 1 if committed manifests are stale

The committed manifests are the source of truth for `kubectl apply -k`; the
`--check` mode lets CI fail if someone edits registry.yaml without regenerating.
"""

from __future__ import annotations

import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
REGISTRY = HERE / "registry.yaml"

_HEADER = (
    "# GENERATED by generate.py from registry.yaml — DO NOT EDIT.\n"
    "# Regenerate: python3 infra/konfig/overlays/tenants/generate.py\n"
)


def _dump(obj: dict) -> str:
    """Deterministic YAML with a generated-file header, insertion-ordered keys."""
    body = yaml.safe_dump(obj, sort_keys=False, default_flow_style=False)
    return _HEADER + body


def _dns_rule(dns: dict) -> dict:
    return {
        "to": [
            {
                "namespaceSelector": {
                    "matchLabels": {"kubernetes.io/metadata.name": dns["namespace"]}
                },
                "podSelector": {
                    "matchLabels": {dns["selectorLabel"]: dns["selectorValue"]}
                },
            }
        ],
        "ports": [
            {"protocol": "UDP", "port": 53},
            {"protocol": "TCP", "port": 53},
        ],
    }


def _konfig_rule(defaults: dict) -> dict:
    return {
        "to": [
            {
                "namespaceSelector": {
                    "matchLabels": {
                        "kubernetes.io/metadata.name": defaults["konfigNamespace"]
                    }
                },
                "podSelector": {"matchLabels": {"app": "konfig"}},
            }
        ],
        "ports": [{"protocol": "TCP", "port": int(defaults["konfigPort"])}],
    }


def _extra_rule(entry: dict) -> dict:
    ports = [{"protocol": "TCP", "port": int(p)} for p in entry.get("ports", [])]
    if "cidr" in entry:
        peer = {"ipBlock": {"cidr": entry["cidr"]}}
    else:
        peer = {
            "namespaceSelector": {
                "matchLabels": {"kubernetes.io/metadata.name": entry["namespace"]}
            }
        }
        if entry.get("podSelector"):
            peer["podSelector"] = {"matchLabels": entry["podSelector"]}
    rule: dict = {"to": [peer]}
    if ports:
        rule["ports"] = ports
    return rule


def _policy(tenant: dict, defaults: dict) -> dict:
    egress = [_dns_rule(defaults["dns"]), _konfig_rule(defaults)]
    egress += [_extra_rule(e) for e in tenant.get("extraEgress", [])]
    return {
        "apiVersion": "networking.k8s.io/v1",
        "kind": "NetworkPolicy",
        "metadata": {
            "name": f"konfig-tenant-egress-{tenant['name']}",
            "namespace": tenant["namespace"],
            "labels": {
                "app.kubernetes.io/managed-by": "konfig-tenant-overlay",
                "konfig.io/tenant": tenant["name"],
            },
        },
        "spec": {
            "podSelector": {"matchLabels": tenant["podSelector"]},
            "policyTypes": ["Egress"],
            "egress": egress,
        },
    }


def render() -> dict[str, str]:
    """Return {filename: file_text} for every generated manifest."""
    reg = yaml.safe_load(REGISTRY.read_text())
    defaults = reg["defaults"]
    tenants = sorted(reg.get("tenants", []), key=lambda t: t["name"])

    out: dict[str, str] = {}
    resources = []
    for tenant in tenants:
        fname = f"networkpolicy-{tenant['name']}.yaml"
        out[fname] = _dump(_policy(tenant, defaults))
        resources.append(fname)

    out["kustomization.yaml"] = _dump(
        {
            "apiVersion": "kustomize.config.k8s.io/v1beta1",
            "kind": "Kustomization",
            "resources": resources,
        }
    )
    return out


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    rendered = render()

    if check:
        stale = []
        for fname, text in rendered.items():
            path = HERE / fname
            if not path.exists() or path.read_text() != text:
                stale.append(fname)
        # Flag committed generated files that the registry no longer produces.
        for path in HERE.glob("networkpolicy-*.yaml"):
            if path.name not in rendered:
                stale.append(f"{path.name} (orphaned)")
        if stale:
            print("stale generated manifests (run generate.py):", file=sys.stderr)
            for s in sorted(stale):
                print(f"  - {s}", file=sys.stderr)
            return 1
        print("tenant overlay manifests up to date.")
        return 0

    for fname, text in rendered.items():
        (HERE / fname).write_text(text)
        print(f"wrote {fname}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
